# Generated by Django 2.0.7 on 2018-08-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_multi_factor_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFactorToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('multi_factor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_multi_factor_authentication.MultiFactorAuthenticationUser')),
            ],
        ),
    ]
