# Generated by Django 2.0.7 on 2018-08-10 09:23

from django.db import migrations, models
import django.db.models.deletion
import django_multi_factor_authentication.models.multi_factor_authentication_token


class Migration(migrations.Migration):

    dependencies = [
        ('django_multi_factor_authentication', '0002_multifactortoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFactorAuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=django_multi_factor_authentication.models.multi_factor_authentication_token._uuid_value, max_length=255)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('multi_factor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_multi_factor_authentication.MultiFactorAuthenticationUser')),
            ],
        ),
    ]
