# Generated by Django 2.0.7 on 2018-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_multi_factor_authentication', '0003_multifactorauthenticationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255, null=True)),
                ('ip', models.CharField(max_length=46)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
